site_name: Gerardo Velasco's Site
nav:
  - Home: index.md
  - Projects: pastProjects.md
  - Education: education.md
  - Hobbies and Fun Facts: hobbies.md

theme:
  name: material
  palette:
    primary: indigo
    accent: orange
  logo: favicon.png